"use client";

import { useEffect } from "react";

export default function OfficeError({ error, reset }: Readonly<{ error: Error & { digest?: string }; reset: () => void }>) {
  useEffect(() => {
    // The digest is generated by Next and contains no database response body.
    if (error.digest) console.error("Office request failed", error.digest);
  }, [error]);
  return (
    <div className="office-page">
      <div className="empty-state" role="alert"><h1>Records are temporarily unavailable.</h1><p>Refresh the current record before repeating any command. Check the connection and try again.</p><button type="button" onClick={reset}>Try again</button></div>
    </div>
  );
}
